/**
 * EmojiTraduci — Database di associazioni parola italiana → emoji
 * Ogni parola mappa a un array: [default, alternativa1, alternativa2, ...]
 */

const emojiDB = {

  /* ── Animali ────────────────────────────────────── */
  'cane':       ['🐕', '🐶', '🦮', '🐩'],
  'cagnolino':  ['🐶', '🐕', '🐩'],
  'gatto':      ['🐱', '🐈', '🐈‍⬛'],
  'gattino':    ['🐱', '🐈'],
  'cavallo':    ['🐴', '🐎', '🦄'],
  'mucca':      ['🐄', '🐮'],
  'maiale':     ['🐷', '🐖'],
  'porco':      ['🐷', '🐖'],
  'pecora':     ['🐑', '🐏'],
  'capra':      ['🐐'],
  'coniglio':   ['🐰', '🐇'],
  'topo':       ['🐭', '🐁'],
  'criceto':    ['🐹'],
  'orso':       ['🐻', '🐻‍❄️'],
  'panda':      ['🐼'],
  'koala':      ['🐨'],
  'tigre':      ['🐯', '🐅'],
  'leone':      ['🦁'],
  'scimmia':    ['🐵', '🐒', '🦧'],
  'gorilla':    ['🦍'],
  'elefante':   ['🐘'],
  'rinoceronte':['🦏'],
  'ippopotamo': ['🦛'],
  'giraffa':    ['🦒'],
  'cammello':   ['🐪', '🐫'],
  'canguro':    ['🦘'],
  'volpe':      ['🦊'],
  'lupo':       ['🐺'],
  'procione':   ['🦝'],
  'puzzola':    ['🦨'],
  'tasso':      ['🦡'],
  'cigno':      ['🦢'],
  'anatra':     ['🦆'],
  'papera':     ['🦆'],
  'gallina':    ['🐔'],
  'gallo':      ['🐓'],
  'pulcino':    ['🐤', '🐣', '🐥'],
  'uccello':    ['🐦', '🦜'],
  'uccellino':  ['🐦'],
  'pinguino':   ['🐧'],
  'gufo':       ['🦉'],
  'aquila':     ['🦅'],
  'fenicottero':['🦩'],
  'pavone':     ['🦚'],
  'pappagallo': ['🦜'],
  'rana':       ['🐸'],
  'rospo':      ['🐸'],
  'coccodrillo':['🐊'],
  'tartaruga':  ['🐢'],
  'serpente':   ['🐍'],
  'biscia':     ['🐍'],
  'lucertola':  ['🦎'],
  'drago':      ['🐉', '🐲'],
  'pesce':      ['🐟', '🐠'],
  'pesciolino': ['🐟', '🐠'],
  'delfino':    ['🐬'],
  'balena':     ['🐳', '🐋'],
  'squalo':     ['🦈'],
  'polpo':      ['🐙'],
  'piovra':     ['🐙'],
  'medusa':     ['🪼'],
  'granchio':   ['🦀'],
  'aragosta':   ['🦞'],
  'gambero':    ['🦐'],
  'lumaca':     ['🐌'],
  'chiocciola': ['🐌'],
  'farfalla':   ['🦋'],
  'ape':        ['🐝'],
  'coccinella': ['🐞'],
  'formica':    ['🐜'],
  'ragno':      ['🕷️', '🕸️'],
  'scorpione':  ['🦂'],
  'zanzara':    ['🦟'],
  'mosca':      ['🪰'],
  'verme':      ['🪱'],
  'cetriolo':   ['🥒'],

  /* ── Cibo & Bevande ────────────────────────────── */
  'pizza':      ['🍕'],
  'pasta':      ['🍝'],
  'spaghetti':  ['🍝'],
  'hamburger':  ['🍔'],
  'panino':     ['🥪'],
  'hotdog':     ['🌭'],
  'hot-dog':    ['🌭'],
  'patatine':   ['🍟'],
  'patatina':   ['🍟'],
  'popcorn':    ['🍿'],
  'cioccolato': ['🍫'],
  'cioccolatino':['🍫'],
  'caramella':  ['🍬'],
  'gelato':     ['🍦', '🍨'],
  'torta':      ['🎂', '🍰'],
  'dolce':      ['🍰', '🧁', '🍩'],
  'biscotto':   ['🍪'],
  'pane':       ['🍞', '🥖', '🥐'],
  'uovo':       ['🥚'],
  'uova':       ['🥚'],
  'formaggio':  ['🧀'],
  'latte':      ['🥛'],
  'caffè':      ['☕'],
  'caffe':      ['☕'],
  'tè':         ['🍵'],
  'te':         ['🍵'],
  'birra':      ['🍺', '🍻'],
  'vino':       ['🍷'],
  'cocktail':   ['🍸', '🍹'],
  'acqua':      ['💧', '🚰'],
  'mela':       ['🍎', '🍏'],
  'pera':       ['🍐'],
  'arancia':    ['🍊'],
  'limone':     ['🍋'],
  'banana':     ['🍌'],
  'anguria':    ['🍉'],
  'cocomero':   ['🍉'],
  'uva':        ['🍇'],
  'fragola':    ['🍓'],
  'ciliegia':   ['🍒'],
  'ciliegie':   ['🍒'],
  'pesca':      ['🍑'],
  'mango':      ['🥭'],
  'ananas':     ['🍍'],
  'cocco':      ['🥥'],
  'noce':       ['🥥'],
  'avocado':    ['🥑'],
  'pomodoro':   ['🍅'],
  'melanzana':  ['🍆'],
  'carota':     ['🥕'],
  'broccoli':   ['🥦'],
  'fungo':      ['🍄'],
  'peperone':   ['🫑'],
  'peperoncino':['🌶️'],
  'insalata':   ['🥬', '🥗'],
  'zucca':      ['🎃'],
  'patata':     ['🥔'],
  'aglio':      ['🧄'],
  'cipolla':    ['🧅'],
  'mais':       ['🌽'],
  'riso':       ['🍚'],
  'zuppa':      ['🍜'],
  'minestra':   ['🍜'],
  'sushi':      ['🍣'],
  'taco':       ['🌮'],
  'burrito':    ['🌯'],
  'kebab':      ['🥙'],
  'waffle':     ['🧇'],
  'pancake':    ['🥞'],
  'frittella':  ['🥞'],
  'miele':      ['🍯'],

  /* ── Emozioni & Sentimenti ─────────────────────── */
  'felice':     ['😊', '😄', '🥳'],
  'contento':   ['😊', '🙂'],
  'triste':     ['😢', '😔', '😞'],
  'arrabbiato': ['😠', '😡', '🤬'],
  'arrabbiata': ['😠', '😡'],
  'rabbia':     ['😡', '🤬'],
  'sorpreso':   ['😲', '😮'],
  'sorpresa':   ['😲', '😮'],
  'spaventato': ['😨', '😱'],
  'paura':      ['😨', '😱'],
  'amore':      ['❤️', '💕', '💖'],
  'bacio':      ['😘', '💋'],
  'risata':     ['😂', '🤣'],
  'riso':       ['😂'],
  'pianto':     ['😭', '🥲'],
  'piangere':   ['😭', '😢'],
  'pensieroso': ['🤔'],
  'pensare':    ['🤔', '💭'],
  'stanco':     ['😴', '😩'],
  'stanchezza': ['😴'],
  'malato':     ['🤒', '🤧'],
  'malattia':   ['🤒'],
  'divertito':  ['😄', '😆'],
  'divertente': ['😄'],
  'confuso':    ['😕', '😵‍💫'],
  'confusione': ['😕'],
  'orgoglioso': ['🥲', '😌'],
  'preoccupato':['😟', '😰'],
  'ansia':      ['😰', '😟'],
  'annoiato':   ['🥱', '😒'],
  'noia':       ['🥱'],
  'entusiasta': ['🤩', '🎉'],
  'entusiasmo': ['🤩'],
  'disgustato': ['🤢'],
  'disgusto':   ['🤢'],
  'geloso':     ['🥴', '😒'],
  'gelosia':    ['🥴'],
  'timido':     ['😳', '👉👈'],
  'timidezza':  ['😳'],
  'furbo':      ['😏', '🦊'],
  'furbizia':   ['😏'],
  'nervoso':    ['😬', '😰'],
  'calmo':      ['😌', '🧘'],
  'calma':      ['😌'],
  'fortunato':  ['🍀', '🤞'],
  'fortuna':    ['🍀'],
  'coraggio':   ['💪', '🦁'],
  'forza':      ['💪'],
  'forte':      ['💪'],
  'debole':     ['😓'],
  'dolore':     ['😖', '🤕'],
  'male':       ['😖', '🤕'],
  'bene':       ['👍', '😊'],
  'ok':         ['👌', '👍'],
  'perfetto':   ['👌', '💯'],
  'fantastico': ['🤩', '✨'],
  'orribile':   ['👎', '💩'],
  'brutto':     ['👎', '😕'],

  /* ── Oggetti quotidiani ────────────────────────── */
  'telefono':   ['📱', '📞'],
  'cellulare':  ['📱'],
  'smartphone': ['📱'],
  'computer':   ['💻', '🖥️'],
  'pc':         ['💻'],
  'orologio':   ['⌚', '🕐'],
  'libro':      ['📖', '📚'],
  'libri':      ['📚'],
  'penna':      ['🖊️', '✒️'],
  'matita':     ['✏️'],
  'chiave':     ['🔑', '🗝️'],
  'chiavi':     ['🔑'],
  'auto':       ['🚗', '🚘'],
  'macchina':   ['🚗', '🚘'],
  'automobile': ['🚗'],
  'bicicletta': ['🚲', '🚴'],
  'bici':       ['🚲'],
  'moto':       ['🏍️'],
  'motorino':   ['🛵'],
  'scooter':    ['🛵'],
  'treno':      ['🚂', '🚆'],
  'aereo':      ['✈️', '🛩️'],
  'aereoporto': ['✈️'],
  'casa':       ['🏠', '🏡'],
  'porta':      ['🚪'],
  'finestra':   ['🪟'],
  'letto':      ['🛏️', '🛌'],
  'sedia':      ['🪑'],
  'tavolo':     ['🪑'],
  'scrivania':  ['🪑'],
  'lampada':    ['💡'],
  'luce':       ['💡'],
  'denaro':     ['💰', '💵'],
  'soldi':      ['💰', '💵', '🤑'],
  'regalo':     ['🎁'],
  'dono':       ['🎁'],
  'pallone':    ['⚽', '🏀'],
  'palla':      ['⚽', '🏀'],
  'chitarra':   ['🎸'],
  'musica':     ['🎵', '🎶'],
  'canzone':    ['🎵'],
  'film':       ['🎬', '🎥'],
  'cinema':     ['🎬', '🎥'],
  'fotocamera': ['📷', '📸'],
  'foto':       ['📸', '🖼️'],
  'televisione':['📺'],
  'tv':         ['📺'],
  'radio':      ['📻'],
  'microfono':  ['🎤'],
  'cuffie':     ['🎧'],
  'ombrello':   ['☂️', '🌂'],
  'occhiali':   ['👓', '🕶️'],
  'valigia':    ['🧳'],
  'borsa':      ['👜', '🎒'],
  'zaino':      ['🎒'],
  'corona':     ['👑'],
  'anello':     ['💍'],
  'candela':    ['🕯️'],
  'mappa':      ['🗺️'],
  'bussola':    ['🧭'],
  'martello':   ['🔨'],
  'chiave-inglese':['🔧'],
  'cacciavite': ['🪛'],
  'forbici':    ['✂️'],
  'coltello':   ['🔪'],
  'cucchiaio':  ['🥄'],
  'forchetta':  ['🍴'],
  'piatto':     ['🍽️'],
  'bicchiere':  ['🥛', '🍷'],
  'tazza':      ['☕'],
  'bottiglia':  ['🍾'],
  'scatola':    ['📦'],
  'pacco':      ['📦'],
  'busta':      ['✉️', '📨'],
  'lettera':    ['✉️'],
  'email':      ['📧'],
  'messaggio':  ['💬', '📩'],
  'calendario': ['📅'],
  'orologio-da-polso':['⌚'],

  /* ── Natura & Meteo ────────────────────────────── */
  'sole':       ['☀️', '🌞'],
  'luna':       ['🌙', '🌛', '🌝'],
  'stella':     ['⭐', '🌟'],
  'stelle':     ['⭐', '🌟', '✨'],
  'nuvola':     ['☁️', '⛅'],
  'nuvole':     ['☁️', '☁️☁️'],
  'pioggia':    ['🌧️', '☔'],
  'piovere':    ['🌧️'],
  'neve':       ['❄️', '🌨️'],
  'nevicare':   ['❄️'],
  'fulmine':    ['⚡', '🌩️'],
  'temporale':  ['⛈️', '🌩️'],
  'arcobaleno': ['🌈'],
  'fuoco':      ['🔥'],
  'fiamma':     ['🔥'],
  'fiamme':     ['🔥'],
  'albero':     ['🌳', '🌲'],
  'alberi':     ['🌳', '🌲'],
  'fiore':      ['🌸', '🌺', '💐'],
  'fiori':      ['💐', '🌸'],
  'rosa':       ['🌹'],
  'girasole':   ['🌻'],
  'tulipano':   ['🌷'],
  'foglia':     ['🍃', '🍂'],
  'montagna':   ['⛰️', '🏔️'],
  'montagne':   ['⛰️'],
  'vulcano':    ['🌋'],
  'isola':      ['🏝️'],
  'spiaggia':   ['🏖️'],
  'mare':       ['🌊', '🏖️'],
  'oceano':     ['🌊'],
  'onda':       ['🌊'],
  'fiume':      ['🏞️'],
  'lago':       ['🏞️'],
  'deserto':    ['🏜️'],
  'parco':      ['🏞️', '🌳'],
  'giardino':   ['🏡', '🌻'],
  'foresta':    ['🌲', '🌳'],
  'giungla':    ['🌴', '🌿'],
  'terra':      ['🌍', '🌎'],
  'mondo':      ['🌍'],
  'pianeta':    ['🪐'],
  'vento':      ['💨', '🌬️'],
  'freddo':     ['🥶', '❄️'],
  'caldo':      ['🥵', '☀️'],
  'ghiaccio':   ['🧊'],
  'cristallo':  ['💎'],

  /* ── Persone & Famiglia ────────────────────────── */
  'uomo':       ['👨', '🧑'],
  'donna':      ['👩', '🧑'],
  'bambino':    ['👶', '🧒'],
  'bambina':    ['👶', '🧒'],
  'bambini':    ['👶', '🧒'],
  'ragazzo':    ['🧑', '👦'],
  'ragazza':    ['🧑', '👧'],
  'famiglia':   ['👨‍👩‍👦', '👪'],
  'amico':      ['🤝', '👫'],
  'amici':      ['👫', '🤝'],
  'amica':      ['🤝', '👭'],
  'nemico':     ['👿', '😈'],
  're':         ['👑', '🤴'],
  'regina':     ['👑', '👸'],
  'principe':   ['🤴'],
  'principessa':['👸'],
  'poliziotto': ['👮', '👮‍♂️'],
  'pompiere':   ['👨‍🚒', '🧑‍🚒'],
  'dottore':    ['👨‍⚕️', '🧑‍⚕️'],
  'medico':     ['👨‍⚕️', '🧑‍⚕️'],
  'infermiere': ['👨‍⚕️'],
  'insegnante': ['👨‍🏫', '🧑‍🏫'],
  'maestro':    ['👨‍🏫'],
  'professore': ['👨‍🏫'],
  'cuoco':      ['👨‍🍳', '🧑‍🍳'],
  'chef':       ['👨‍🍳'],
  'artista':    ['👨‍🎨', '🧑‍🎨'],
  'musicista':  ['👨‍🎤', '🧑‍🎤'],
  'cantante':   ['👨‍🎤', '🧑‍🎤'],
  'astronauta': ['👨‍🚀', '🧑‍🚀'],
  'supereroe':  ['🦸', '🦸‍♂️'],
  'mago':       ['🧙', '🧙‍♂️'],
  'strega':     ['🧙‍♀️'],
  'vampiro':    ['🧛', '🧛‍♂️'],
  'zombie':     ['🧟', '🧟‍♂️'],
  'alieno':     ['👽'],
  'robot':      ['🤖'],
  'fantasma':   ['👻'],
  'mostro':     ['👾', '👹'],
  'angelo':     ['👼'],
  'diavolo':    ['😈'],
  'dio':        ['🙏', '☁️'],
  'babbo-natale':['🎅'],
  'babbo natale':['🎅'],
  'natale':     ['🎄', '🎅'],

  /* ── Azioni / Verbi ────────────────────────────── */
  'correre':    ['🏃', '🏃‍♂️'],
  'corsa':      ['🏃'],
  'camminare':  ['🚶', '🚶‍♂️'],
  'passeggiare':['🚶'],
  'nuotare':    ['🏊', '🏊‍♂️'],
  'nuoto':      ['🏊'],
  'ballare':    ['💃', '🕺'],
  'ballo':      ['💃', '🕺'],
  'danza':      ['💃'],
  'cantare':    ['🎤', '🎶'],
  'dormire':    ['😴', '🛌'],
  'sonno':      ['😴'],
  'sognare':    ['💭', '🌙'],
  'sogno':      ['💭'],
  'mangiare':   ['🍽️', '😋'],
  'cibo':       ['🍽️'],
  'bere':       ['🍺', '🥤'],
  'leggere':    ['📖', '📚'],
  'lettura':    ['📖'],
  'scrivere':   ['✍️', '📝'],
  'scrittura':  ['✍️'],
  'disegnare':  ['🎨'],
  'disegno':    ['🎨'],
  'ascoltare':  ['👂', '🎧'],
  'ascolto':    ['👂'],
  'vedere':     ['👀'],
  'vista':      ['👀'],
  'parlare':    ['💬', '🗣️'],
  'discorso':   ['🗣️'],
  'amare':      ['❤️', '💕'],
  'odiare':     ['👿', '💔'],
  'odio':       ['💔'],
  'ridere':     ['😂', '🤣'],
  'urlare':     ['📢', '🗣️'],
  'gridare':    ['📢'],
  'combattere': ['⚔️', '🥊'],
  'lotta':      ['⚔️', '🥊'],
  'vincere':    ['🏆', '🥇'],
  'vittoria':   ['🏆'],
  'perdere':    ['📉', '😞'],
  'sconfitta':  ['📉'],
  'viaggiare':  ['🧳', '✈️'],
  'viaggio':    ['🧳', '✈️'],
  'volare':     ['✈️', '🕊️'],
  'volo':       ['✈️'],
  'guidare':    ['🚗'],
  'guida':      ['🚗'],
  'comprare':   ['🛒', '💳'],
  'shopping':   ['🛒'],
  'vendere':    ['💰', '💵'],
  'lavorare':   ['💼', '👨‍💼'],
  'lavoro':     ['💼'],
  'studiare':   ['📚', '🎓'],
  'studio':     ['📚'],
  'giocare':    ['🎮', '🎲'],
  'gioco':      ['🎮', '🎲'],
  'aspettare':  ['⏳', '🕐'],
  'attesa':     ['⏳'],
  'cercare':    ['🔍', '🔎'],
  'ricerca':    ['🔍'],
  'trovare':    ['🔍', '✅'],
  'aiutare':    ['🆘', '🤝'],
  'aiuto':      ['🆘'],
  'chiamare':   ['📞', '📲'],
  'chiamata':   ['📞'],
  'aprire':     ['🔓', '🚪'],
  'chiudere':   ['🔒', '🚪'],
  'salire':     ['⬆️', '📈'],
  'scendere':   ['⬇️', '📉'],
  'entrare':    ['🚪', '⬅️'],
  'uscire':     ['🚪', '➡️'],
  'arrivare':   ['🏁', '✅'],
  'partire':    ['🚀', '✈️'],
  'iniziare':   ['▶️', '🚀'],
  'inizio':     ['▶️'],
  'finire':     ['🏁', '⏹️'],
  'fine':       ['🏁'],
  'costruire':  ['🔨', '🏗️'],
  'rompere':    ['💥', '🔨'],
  'rotto':      ['💥'],
  'aggiustare': ['🔧', '🛠️'],
  'pulire':     ['🧹', '🧼'],
  'pulizia':    ['🧹'],
  'sporco':     ['💩', '🤢'],
  'cucinare':   ['👨‍🍳', '🍳'],
  'cucina':     ['🍳', '👨‍🍳'],
  'fumare':     ['🚬', '💨'],

  /* ── Luoghi ────────────────────────────────────── */
  'scuola':     ['🏫'],
  'università': ['🎓', '🏫'],
  'ospedale':   ['🏥'],
  'chiesa':     ['⛪'],
  'banca':      ['🏦'],
  'ristorante': ['🍽️', '🍴'],
  'bar':        ['☕', '🍺'],
  'pub':        ['🍺'],
  'negozio':    ['🏪', '🛍️'],
  'supermercato':['🏪', '🛒'],
  'teatro':     ['🎭'],
  'stadio':     ['🏟️'],
  'stazione':   ['🚉'],
  'porto':      ['⚓', '🚢'],
  'castello':   ['🏰'],
  'ponte':      ['🌉'],
  'torre':      ['🗼', '🏰'],
  'città':      ['🏙️', '🌆'],
  'citta':      ['🏙️'],
  'paese':      ['🏘️'],
  'villaggio':  ['🏘️'],
  'spazio':     ['🚀', '🌌'],

  /* ── Tempo ─────────────────────────────────────── */
  'oggi':       ['📅'],
  'domani':     ['📅', '🔜'],
  'ieri':       ['📅', '🔙'],
  'ora':        ['🕐', '⏰'],
  'adesso':     ['🕐'],
  'subito':     ['⚡', '🏃'],
  'minuto':     ['⏱️'],
  'giorno':     ['📅', '☀️'],
  'notte':      ['🌙', '🌃'],
  'settimana':  ['📅'],
  'mese':       ['📅'],
  'anno':       ['📅', '🗓️'],
  'mattina':    ['🌅', '☀️'],
  'pomeriggio': ['🌤️', '☀️'],
  'sera':       ['🌆', '🌇'],
  'mezzogiorno':['☀️', '🕛'],
  'mezzanotte': ['🌙', '🕛'],
  'compleanno': ['🎂', '🎉'],
  'pasqua':     ['🐰', '🥚'],
  'halloween':  ['🎃', '👻'],
  'capodanno':  ['🎆', '🥂'],
  'festa':      ['🎉', '🎊'],
  'vacanza':    ['🏖️', '✈️'],
  'vacanze':    ['🏖️', '✈️'],

  /* ── Colori ────────────────────────────────────── */
  'rosso':      ['🔴', '❤️'],
  'blu':        ['🔵', '💙'],
  'azzurro':    ['🔵', '🩵'],
  'verde':      ['🟢', '💚'],
  'giallo':     ['🟡', '💛'],
  'arancione':  ['🟠', '🧡'],
  'viola':      ['🟣', '💜'],
  'nero':       ['⚫', '🖤'],
  'bianco':     ['⚪', '🤍'],
  'marrone':    ['🟤', '🤎'],
  'rosa':       ['💖', '🩷'],
  'grigio':     ['🩶', '🪨'],
  'oro':        ['🥇', '🌟'],
  'argento':    ['🥈', '🪙'],

  /* ── Sport ─────────────────────────────────────── */
  'calcio':     ['⚽', '🥅'],
  'basket':     ['🏀'],
  'tennis':     ['🎾'],
  'pallavolo':  ['🏐'],
  'volley':     ['🏐'],
  'rugby':      ['🏉'],
  'baseball':   ['⚾'],
  'golf':       ['⛳', '🏌️'],
  'nuoto':      ['🏊'],
  'ciclismo':   ['🚴'],
  'sci':        ['⛷️'],
  'snowboard':  ['🏂'],
  'surf':       ['🏄', '🏄‍♂️'],
  'boxe':       ['🥊'],
  'pugilato':   ['🥊'],
  'karate':     ['🥋'],
  'arti-marziali':['🥋'],
  'yoga':       ['🧘', '🧘‍♀️'],
  'palestra':   ['🏋️', '💪'],
  'pesi':       ['🏋️'],

  /* ── Tecnologia ────────────────────────────────── */
  'internet':   ['🌐'],
  'web':        ['🌐'],
  'wifi':       ['📶'],
  'bluetooth':  ['🛜'],
  'batteria':   ['🔋'],
  'caricatore': ['🔌'],
  'cavo':       ['🔌'],
  'stampante':  ['🖨️'],
  'satellite':  ['🛰️'],
  'razzo':      ['🚀'],
  'missile':    ['🚀'],
  'disco':      ['💿', '📀'],
  'cd':         ['💿'],
  'hard-disk':  ['💽'],
  'chip':       ['💾'],
  'tastiera':   ['⌨️'],
  'mouse':      ['🖱️'],
  'schermo':    ['🖥️'],
  'monitor':    ['🖥️'],
  'gamepad':    ['🎮'],
  'joystick':   ['🕹️'],

  /* ── Simboli & Segni ───────────────────────────── */
  'cuore':      ['❤️', '💕', '🫶'],
  'bacio':      ['💋', '😘'],
  'pace':       ['☮️', '✌️'],
  'guerra':     ['⚔️', '💣'],
  'pericolo':   ['⚠️', '☢️'],
  'attenzione': ['⚠️'],
  'veleno':     ['☠️', '🧪'],
  'radioattivo':['☢️'],
  'divieto':    ['🚫', '⛔'],
  'vietato':    ['🚫'],
  'check':      ['✅', '✔️'],
  'croce':      ['❌', '✖️'],
  'stella':     ['⭐', '🌟'],
  'freccia':    ['➡️', '⬆️'],
  'su':         ['⬆️', '👆'],
  'giù':        ['⬇️', '👇'],
  'giu':        ['⬇️'],
  'destra':     ['➡️', '👉'],
  'sinistra':   ['⬅️', '👈'],
  'riciclo':    ['♻️'],
  'infinito':   ['♾️'],
  'percentuale':['💯'],
  'cento':      ['💯'],
  'idea':       ['💡', '🤔'],
  'lampadina':  ['💡'],
  'target':     ['🎯'],
  'obiettivo':  ['🎯'],
  'premio':     ['🏆', '🎖️'],
  'medaglia':   ['🏅', '🎖️'],

  /* ── Espressioni comuni ────────────────────────── */
  'ciao':       ['👋', '🤚'],
  'salve':      ['👋'],
  'buongiorno': ['☀️', '👋'],
  'buonasera':  ['🌆', '👋'],
  'buonanotte': ['🌙', '😴'],
  'arrivederci':['👋', '👋😊'],
  'grazie':     ['🙏', '💝'],
  'prego':      ['🤝', '😊'],
  'scusa':      ['🙏', '😔'],
  'scusi':      ['🙏'],
  'per-favore': ['🥺', '🙏'],
  'per favore': ['🥺', '🙏'],
  'bravo':      ['👏', '👍'],
  'brava':      ['👏', '👍'],
  'bello':      ['😍', '✨'],
  'bella':      ['😍', '✨'],
  'bellissimo': ['😍', '🤩'],
  'wow':        ['😮', '🤩'],
  'che-bello':  ['😍'],
  'evviva':     ['🎉', '🥳'],
  'urrà':       ['🎉'],
  'uffa':       ['😩', '😤'],
  'boh':        ['🤷', '🤷‍♂️'],
  'mah':        ['🤷'],
  'chissà':     ['🤷'],
  'chissa':     ['🤷'],
  'magari':     ['🤞', '🙏'],
  'forse':      ['🤷', '🤔'],
  'boom':       ['💥', '🧨'],
  'esplosione': ['💥'],
  'esplodere':  ['💥'],
  'bomba':      ['💣', '🧨'],
  'silenzio':   ['🤫', '🔇'],
  'zitto':      ['🤫'],
  'segreto':    ['🤫', '🤐'],
  'attenzione': ['⚠️', '👀'],
  'urgente':    ['🚨', '⚠️'],
  'veloce':     ['⚡', '💨'],
  'lento':      ['🐌', '🦥'],
  'grande':     ['🐘', '📈'],
  'piccolo':    ['🐭', '📉'],
  'alto':       ['📈', '⬆️'],
  'basso':      ['📉', '⬇️'],
  'nuovo':      ['🆕', '✨'],
  'vecchio':    ['👴', '📜'],
  'giovane':    ['👶', '🌱'],
  'pieno':      ['🈵'],
  'vuoto':      ['🈳'],
  'pulito':     ['✨', '🧼'],
  'intelligente':['🧠', '🤓'],
  'stupido':    ['🤪', '🥴'],
  'ricco':      ['💰', '🤑'],
  'povero':     ['😢', '🫗'],
  'famoso':     ['🌟', '⭐'],
  'importante': ['⭐', '❗'],
  'urgente':    ['🚨'],
  'segreto':    ['🤫'],
  'magico':     ['✨', '🪄'],
  'magia':      ['🪄', '✨'],
  'divertimento':['🎉', '😄'],
  'scherzo':    ['😜', '🃏'],
  'risata':     ['😂'],
  'sorriso':    ['😊', '🙂'],
};

/**
 * Normalizza una parola per il lookup (minuscolo, senza accenti base)
 */
function normalize(word) {
  let w = word.toLowerCase().trim();
  // Rimuovi punteggiatura adiacente
  w = w.replace(/^[.,;:!?¿¡()\[\]{}""''«»…]+/, '');
  w = w.replace(/[.,;:!?¿¡()\[\]{}""''«»…]+$/, '');
  return w;
}

/**
 * Prova forme derivate semplici (singolare/plurale, verbi)
 */
function tryVariants(word) {
  const variants = [];

  // Plurali maschili -i → -o oppure -i → -e
  if (word.endsWith('i') && word.length > 2) {
    variants.push(word.slice(0, -1) + 'o');
    variants.push(word.slice(0, -1) + 'e');
  }
  // Plurali femminili -e → -a
  if (word.endsWith('e') && word.length > 2) {
    variants.push(word.slice(0, -1) + 'a');
  }

  // Verbi: infinito -are, -ere, -ire
  // Participio passato -ato, -uto, -ito → infinito
  if (word.endsWith('ato') && word.length > 4) {
    variants.push(word.slice(0, -3) + 'are');
  }
  if (word.endsWith('uto') && word.length > 4) {
    variants.push(word.slice(0, -3) + 'ere');
  }
  if (word.endsWith('ito') && word.length > 4) {
    variants.push(word.slice(0, -3) + 'ire');
  }

  // Gerundio -ando, -endo → infinito
  if (word.endsWith('ando') && word.length > 5) {
    variants.push(word.slice(0, -4) + 'are');
  }
  if (word.endsWith('endo') && word.length > 5) {
    variants.push(word.slice(0, -4) + 'ere');
    variants.push(word.slice(0, -4) + 'ire');
  }

  return variants;
}

/**
 * Cerca l'emoji per una parola. Restituisce l'array di emoji o null.
 */
function lookup(word) {
  const clean = normalize(word);
  if (!clean) return null;

  // 1. Match esatto
  if (emojiDB[clean]) return emojiDB[clean];

  // 2. Prova varianti morfologiche
  const variants = tryVariants(clean);
  for (const v of variants) {
    if (emojiDB[v]) return emojiDB[v];
  }

  return null;
}

/**
 * Traduce un testo in token di tipo {type, text, emojis, resolvedEmoji, resolvedIndex}
 * type: 'word' | 'space' | 'punctuation'
 */
function translate(text) {
  if (!text || !text.trim()) return [];

  // Tokenizzazione: separiamo parole, spazi e punteggiatura
  const tokens = [];
  const regex = /(\s+|[^\w\s]+|[\wàèéìòù'’]+)/gi;
  let match;

  while ((match = regex.exec(text)) !== null) {
    const token = match[1];
    if (/^\s+$/.test(token)) {
      tokens.push({ type: 'space', text: token, emojis: null, resolvedEmoji: null, resolvedIndex: -1 });
    } else if (/^[^\w\s]+$/.test(token)) {
      tokens.push({ type: 'punctuation', text: token, emojis: null, resolvedEmoji: null, resolvedIndex: -1 });
    } else {
      const emojis = lookup(token);
      tokens.push({
        type: 'word',
        text: token,
        originalText: token,
        emojis: emojis,
        resolvedEmoji: emojis ? emojis[0] : null,
        resolvedIndex: emojis ? 0 : -1,
      });
    }
  }

  return tokens;
}

export { emojiDB, lookup, translate, normalize };
